//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.296
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoContactSyncMod.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoContactSyncMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon Idle {
            get {
                object obj = ResourceManager.GetObject("Idle", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finalizing ähnelt.
        /// </summary>
        internal static string SettingsForm_FinalizeSync {
            get {
                return ResourceManager.GetString("SettingsForm_FinalizeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging off Google ähnelt.
        /// </summary>
        internal static string SettingsForm_GoogleLogoff {
            get {
                return ResourceManager.GetString("SettingsForm_GoogleLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging into Google ähnelt.
        /// </summary>
        internal static string SettingsForm_GoogleLogon {
            get {
                return ResourceManager.GetString("SettingsForm_GoogleLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initializing ähnelt.
        /// </summary>
        internal static string SettingsForm_InitializeSync {
            get {
                return ResourceManager.GetString("SettingsForm_InitializeSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging off Outlook ähnelt.
        /// </summary>
        internal static string SettingsForm_OutlookLogoff {
            get {
                return ResourceManager.GetString("SettingsForm_OutlookLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging into Outlook ähnelt.
        /// </summary>
        internal static string SettingsForm_OutlookLogon {
            get {
                return ResourceManager.GetString("SettingsForm_OutlookLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resetting Matches ähnelt.
        /// </summary>
        internal static string SettingsForm_ResetMatches {
            get {
                return ResourceManager.GetString("SettingsForm_ResetMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please fill out the settings form. ähnelt.
        /// </summary>
        internal static string SettingsForm_SettingsIncomplete {
            get {
                return ResourceManager.GetString("SettingsForm_SettingsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Syncing ähnelt.
        /// </summary>
        internal static string SettingsForm_SyncContacts {
            get {
                return ResourceManager.GetString("SettingsForm_SyncContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Already in progress. ähnelt.
        /// </summary>
        internal static string SettingsForm_SyncPending {
            get {
                return ResourceManager.GetString("SettingsForm_SyncPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last sync: {0:t}.
        /// Synced: {2} out of {1}
        /// Deleted: {3}
        /// Skipped: {4}
        /// Errors: {5} ähnelt.
        /// </summary>
        internal static string SettingsForm_SyncResult {
            get {
                return ResourceManager.GetString("SettingsForm_SyncResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please save or cancel the changes to the settings first. ähnelt.
        /// </summary>
        internal static string SettingsForm_UnsavedSettings {
            get {
                return ResourceManager.GetString("SettingsForm_UnsavedSettings", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Work_01 {
            get {
                object obj = ResourceManager.GetObject("Work_01", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_02 {
            get {
                object obj = ResourceManager.GetObject("Work_02", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_03 {
            get {
                object obj = ResourceManager.GetObject("Work_03", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_04 {
            get {
                object obj = ResourceManager.GetObject("Work_04", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_05 {
            get {
                object obj = ResourceManager.GetObject("Work_05", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_06 {
            get {
                object obj = ResourceManager.GetObject("Work_06", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_07 {
            get {
                object obj = ResourceManager.GetObject("Work_07", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_08 {
            get {
                object obj = ResourceManager.GetObject("Work_08", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_09 {
            get {
                object obj = ResourceManager.GetObject("Work_09", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_10 {
            get {
                object obj = ResourceManager.GetObject("Work_10", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_11 {
            get {
                object obj = ResourceManager.GetObject("Work_11", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Work_12 {
            get {
                object obj = ResourceManager.GetObject("Work_12", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
